#! /usr/bin/env python
import sys
import os
import shutil
inlist= sys.argv
if((len(inlist)<4)or(inlist[1]!='-j')or(inlist[3]!='-np')):
    print 'Usage: '+inlist[0]+' -j jobname -np numofnodes exec arglist'
else:
    jobname = 'pbs_'+inlist[2]
    numofnodes = inlist[4]
    execname = inlist[5]
    newexecname = jobname+'_'+execname
    shutil.copy2(execname, newexecname)
    if(len(inlist)<7):
        args = ''
    else:
        args = inlist[6:]
    arglist = ''
    for x in args:
        arglist = arglist+' '+x   
    file = open(jobname+'.pbs','w')
    file.write('#!/bin/bash\n')
    file.write('#SBATCH -J '+jobname+'\n')
    file.write('#SBATCH -n '+numofnodes+' \n')
    file.write('#SBATCH -N '+numofnodes+' \n')
    file.write('#SBATCH -t 01:00:00 \n')
    file.write('#SBATCH -p development \n')
    currentdir = os.getcwd()
    file.write('cd '+currentdir+'\n')
    file.write('ibrun -np '+numofnodes+' '+newexecname+' '+arglist+' > '+currentdir+'/'+jobname+'.txt\n')
    file.write('rm core*\n')
    file.close()
    os.execvp('sbatch',['sbatch',jobname+'.pbs'])



