#! /usr/bin/env python
from __future__ import print_function
import os, sys
assert len(sys.argv) == 2
jname = sys.argv[1]

f = os.popen('showq -u')
for line in f:
    ll = line.split()
    if len(ll) > 2 and ll[2]=='tg456871' and ll[1]==jname:
        jid = ll[0]
        break
f.close()
cmd = 'scancel ' + jid
print(cmd)
os.system(cmd)
