#! /usr/bin/env python
import sys
import os
import commands
rval, uname = commands.getstatusoutput('uname -a')
ver = sys.argv[1]
indx = uname.find(ver)
if indx!=-1:
    print(ver+' to be removed appears in '+uname);
    print('unsafe to remove kernel?')
    print('exiting')
    exit(0)
if not(ver[0]=='3' and ver[1]=='.' and ver[2]=='8'):
    print('version not in valid format')
    print('exiting')
    exit(0)
list = os.listdir('/boot')
for x in list:
    if(x.find(ver)>=0):
        cmd = 'rm /boot/'+x
        print cmd
        os.system(cmd)
list = os.listdir('/lib/modules')
for x in list:
    if(x.find(ver)>=0):
        cmd = 'rm -rf /lib/modules/'+x
        print cmd
        os.system(cmd)
cmd = 'update-grub2'
print cmd 
os.system(cmd)    



