include ../makevars.mk


Aitken.o: Aitken.cpp
include Aitken.d

Leibniz.o: Leibniz.cpp
include Leibniz.d

Logseries.o: Logseries.cpp
include Logseries.d

Leibniz.exe: Leibniz.o Aitken.o

LogSeries.exe: LogSeries.exe Aitken.o