include ../makevars.mk
LIBS := $(MKLLIBS)
CFLAGSXX := -fno-inline-functins $(MKLINC)

blockmult.o: blockmult.cpp
include blockmult.d

test_block.o: test_block.cpp
include test_block.d

time_block.o: time_block.cpp
include time_block.d

