#! /usr/bin/env python
import sys
import os
import shutil
inlist = sys.argv
if((len(inlist)<2)or(inlist[1] != '-j')):
    print 'Usage: '+inlist[0]+' -j jobname execname arglist'
else:
    jobname = 'pbs_'+inlist[2]
    execname = inlist[3]
    newexecname = 'pbs_'+inlist[2]+'_'+inlist[3];
    shutil.copy2(execname, newexecname);
    if(len(inlist)< 5):
        args = ''
    else:
        args = inlist[5:]
    arglist = ''
    for x in args:
        arglist = arglist+' '+x
    file = open(jobname+'.pbs','w')
    file.write('#! /bin/sh \n')
    file.write('#$ -N '+jobname+'\n')
    file.write('#$ -pe 1way 12 \n');
    file.write('#$ -l h_rt=00:15:00 \n');
    file.write('#$ -q development \n')
    file.write('#$ -j y \n');
    file.write('#$ -V\n')
    file.write('#$ -cwd \n');
    currentdir = os.getcwd();
    file.write(newexecname+' '+arglist+' > '+currentdir+'/'+jobname+'.txt\n')
    file.close()
    os.execvp('qsub',['qsub',jobname+'.pbs'])
